# Rafael Nunes Santana - 201800215

### Pesquisa Operacional - Laboratório 1

Primeiramente, vamos improtar o numpy e criar uma função de utilidade:

In [44]:
import numpy as np

def imprime_vetor_e_shape(vetor): 
    print("vetor:\n", vetor)
    print("shape:", vetor.shape)

E então criamos um vetor linha:

In [45]:
vetor_y = np.array([[3, 4, 5]])
imprime_vetor_e_shape(vetor_y)

vetor:
 [[3 4 5]]
shape: (1, 3)


E um coluna:

In [46]:
vetor_x = np.array([[1], [2], [3]])
imprime_vetor_e_shape(vetor_x)

vetor:
 [[1]
 [2]
 [3]]
shape: (3, 1)


Criando uma matriz:

In [47]:
matriz = np.array([[10, 9, 8],
                   [7, 6, 5],
                   [4, 3, 2]])
imprime_vetor_e_shape(matriz)

vetor:
 [[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
shape: (3, 3)


matriz de zeors:

In [48]:
matriz_zeros = np.zeros((3, 4), dtype=int)
imprime_vetor_e_shape(matriz_zeros)

vetor:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
shape: (3, 4)


Criando um vetor com uma série aritimética:

In [49]:
serie = np.arange(0, 100 ,5)
imprime_vetor_e_shape(serie)

vetor:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
shape: (20,)


Operações com vetores/matrizes:

In [50]:
print(matriz * 4)
print(serie / 5)

[[40 36 32]
 [28 24 20]
 [16 12  8]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


Multiplicação de matrizes:

In [51]:
A = np.array([[2, 3, 1],
              [-1, 0, 2]])

B = np.array([[1, -2],
              [0, 5],
              [4, 1]])

imprime_vetor_e_shape(A.dot(B))

vetor:
 [[ 6 12]
 [ 7  4]]
shape: (2, 2)


Elevando uma matriz ao quadrado:

In [52]:
# primeira forma:
imprime_vetor_e_shape(A ** 2)

# segunda forma (só funciona para matrizes quadradas então não vamos executar):
# imprime_vetor_e_shape(A.dot(A))

vetor:
 [[4 9 1]
 [1 0 4]]
shape: (2, 3)


Produto interno (produto escalar):

In [55]:
imprime_vetor_e_shape(vetor_x.sum())
print()
imprime_vetor_e_shape(vetor_y.sum())

vetor:
 6
shape: ()

vetor:
 12
shape: ()


Produto externo (produto vetorial):

In [59]:
imprime_vetor_e_shape(vetor_x.dot(vetor_y))
print()
imprime_vetor_e_shape(vetor_y.dot(vetor_x))
print()
# ou
imprime_vetor_e_shape(vetor_x * vetor_y)
print()
imprime_vetor_e_shape(vetor_y * vetor_x)

vetor:
 [[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]
shape: (3, 3)

vetor:
 [[26]]
shape: (1, 1)

vetor:
 [[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]
shape: (3, 3)

vetor:
 [[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]
shape: (3, 3)
