# Rafael Nunes Santana - 201800215

### Atividade 3 - Pesquisa Operacional I

Nessa atividade vamos implementar o algorítimo de eliminação de Gauss-Jordan para calcular a inversa de uma matriz e compará-lo com o algorítimo implementado no numpy (numpy.linalg.inv())

In [1]:
import numpy as np
import numpy.matlib
from random import randrange

In [2]:
def inversa(matriz: np.matrix) -> np.matrix:
    # Pegando as dimensões da matriz e verificando se ela é quadrada
    linhas, colunas = matriz.shape
    
    if linhas != colunas:
        raise Exception("Somente matrizes quadradas são invertíveis! Shape da matriz: {} x {}".format(linhas, colunas))
    
    # pegando o tipo dos elementos da matriz
    dtype = matriz.dtype
    
    # alocando a matriz que irá conter uma cópia da matriz original no lado esquerdo (que se tornará a identidade) 
    # e a matriz identidade de tamanho linhas x linhas no lado direito (que se tornará a matriz inversa)
    mat = np.empty([linhas, colunas * 2], dtype=dtype)
    mat[0:linhas, 0:colunas] = matriz
    mat[0:linhas, colunas:colunas * 2] = np.matrix(np.identity(linhas, dtype=dtype))

    for i in range(0, linhas):
    
        # transformando o elemento da diagonal princial em 1 da matriz do lado esquerdo
        if mat[i, i] != 1:
            mat[i] /= mat[i, i]
    
        # transformando os elementos das linhas restantes da matriz do lado esquerdo em 0
        for k in range(0, linhas):
            # não realizamos essa operação na digonal principal (deve ser 1 e não 0)
            if i == k:
                continue
        
            # zerando o elemento k x i
            mat[k] -= mat[i] * mat[k, i] / mat[i, i]
        
    # retornando a matriz do lado direito (que se tornou a inversa)
    return mat[0:linhas, colunas:colunas * 2]

In [3]:
# testando com o exemplo da atividade e comparando com a função do numpy
matriz = np.mat([[1., 1., 1.], [2., 1., 4.], [2., 3., 5.]])

# função de utilidade
def compara_com_numpy(matriz: np.matrix) -> None:  
    inversa_manual = inversa(matriz)
    inversa_numpy = np.linalg.inv(matriz)

    print("Inversa com o algórítmo implementado:\n", inversa_manual, "\n")
    print("Inversa com o algórítmo do numpy:\n", inversa_numpy, "\n")
    
    print("Multiplicando nossa inversa pela matriz tentando obter a identidade:\n", inversa_manual.dot(matriz), "\n")
    
compara_com_numpy(matriz)

Inversa com o algórítmo implementado:
 [[ 1.4  0.4 -0.6]
 [ 0.4 -0.6  0.4]
 [-0.8  0.2  0.2]] 

Inversa com o algórítmo do numpy:
 [[ 1.4  0.4 -0.6]
 [ 0.4 -0.6  0.4]
 [-0.8  0.2  0.2]] 

Multiplicando nossa inversa pela matriz tentando obter a identidade:
 [[ 1.00000000e+00  0.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]] 



Vamos testar com mais algumas matrizes aleatórias:

In [4]:
for _ in range (0, 20):
    # sorteando um tamanho entre 2 e 5
    tamanho = randrange(2, 6)
    
    # gerando uma matriz de float64 aleatória
    rand_matrix = np.matlib.randn((tamanho, tamanho))
    
    compara_com_numpy(rand_matrix)

Inversa com o algórítmo implementado:
 [[-0.03971995 -1.6694503 ]
 [ 0.82818135 -1.77702939]] 

Inversa com o algórítmo do numpy:
 [[-0.03971995 -1.6694503 ]
 [ 0.82818135 -1.77702939]] 

Multiplicando nossa inversa pela matriz tentando obter a identidade:
 [[1.00000000e+00 8.51127316e-17]
 [2.26681064e-17 1.00000000e+00]] 

Inversa com o algórítmo implementado:
 [[  1.84514917   0.84693721  -0.74898186   0.24501237  -4.2178017 ]
 [ -3.17155932  -1.67562565   0.94934699  -0.59744898   5.85074803]
 [  1.28924795   0.76818455  -0.06430097   0.51117246  -2.75925621]
 [  8.85866687   4.39939872  -2.35308062  -1.1985482  -12.7300376 ]
 [  4.27567377   1.67912656  -0.91671061  -0.59523616  -5.49712349]] 

Inversa com o algórítmo do numpy:
 [[  1.84514917   0.84693721  -0.74898186   0.24501237  -4.2178017 ]
 [ -3.17155932  -1.67562565   0.94934699  -0.59744898   5.85074803]
 [  1.28924795   0.76818455  -0.06430097   0.51117246  -2.75925621]
 [  8.85866687   4.39939872  -2.35308062  -1.1985482

Como podemos ver acima, o algoritmo implementado por nós produz resultados basicamente idênticos à função nativa do numpy, e atende a definição de função Inversa. Existem pequenos erros de arredondamento esperados ao se trabalhar com pontos flutuantes que nos impedem de comparar diretamente nossos resultados com os resultados do numpy.

Esses erros surgem devido à forma como as operações com números de pontos flutuantes são realizadas. A maioria das linguagens segue o padrão IEEE 754 para que as operações arritméticas possam ser realizadas utilizando componentes diretos do processador, ganhando muita performance a troco de pequenos erros.

### Sobre as limitações do métododo:

O método de eliminação de Gauss-Jordan pode ser considerado um método ingênuo pois durante as iterações é possível que venham a ocorrer divisões por zero sem qualquer tipo de verificação, o que leva a um erro onde deveria ter sido possível calcular o inverso da matriz. No nosso código essa divisão pode ocorrer nas linhas:

mat[i] /= mat[i, i] e

mat[k] -= mat[i] * mat[k, i] / mat[i, i]

Caso o elemento em [i, i] (diagonal principal) seja zero. Veja abaixo:

In [5]:
matriz = np.mat([[0., 5.], [1., 2.]])
inversa(matriz)

<ipython-input-2-b120bf309f14>:21: RuntimeWarning: divide by zero encountered in true_divide
  mat[i] /= mat[i, i]
<ipython-input-2-b120bf309f14>:21: RuntimeWarning: invalid value encountered in true_divide
  mat[i] /= mat[i, i]


array([[nan, nan],
       [nan, nan]])

Veja que o algorítmo do numpy (mais sofisticado) consegue encontrar a inversa dessa matriz sem problemas:

In [6]:
matriz = np.mat([[0., 5.], [1., 2.]])
np.linalg.inv(matriz)

matrix([[-0.4,  1. ],
        [ 0.2,  0. ]])